### ISSUE TITLE
on Windows?

### ISSUE THREAD

**Issue by bvarga** [kloni/node-prolog-swi#3]
I'm trying to install it on windows, without luck. The latest swipl 6.2.6 doesn't have swipl.lib in lib folder, the 5.10.2 has, but I got other error messages when running `node-gyp build` 

```
libswipl.obj : error LNK2001: unresolved external symbol PL_term_type [c:\node\prolog\node-prolog-swi\build\libswipl.vcxproj]
libswipl.obj : error LNK2001: unresolved external symbol PL_get_integer [c:\node\prolog\node-prolog-swi\build\libswipl.vcxproj]
```

Is there a recipe to make it work under windows (7 64bit)

**Comment by sebgod** [comment]
Well, I've forked it and made it work on my machine, Win7x64 SWI 64 bit Installation , and moved to gyp
https://github.com/sebgod/node-prolog-swi

**Comment by bvarga** [comment]
Thanks, now I can build it, but when I'm trying to run the tests `node tests\a.js`, I got the following error:

```
module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: The specified module could not be found.
c:\node\swipl\node-prolog-swi\libswipl.node
    at Object.Module._extensions..node (module.js:485:11)
```

the libswipl.node is there, and the other files from the build/release folder.

any ideas? 
(I have node 0.8.11)

**Comment by sebgod** [comment]
I have following variables set in a batch script:

set SWI_HOME_DIR=C:\Program Files\swipl
set path=%PATH%;%SWI_HOME_DIR%\bin

**Comment by bvarga** [comment]
I have those too, I think there are missing dependencies of `libswipl.node` (at least [dependencywalker](http://www.dependencywalker.com/) complains)

these are the missing dependencies:

```
API-MS-WIN-CORE-COM-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-0.DLL
DCOMP.DLL
IESHIMS.DLL
```

Now I'm trying with node 0.10.5, and swi-prolog 6.2.6, Windows sdk 7.1 installed, and I'm using VS2010 Express to build the project, now the error stack:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.
c:\node\node-prolog-swi\libswipl.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\node\node-prolog-swi\swipl.js:24:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

So I think there's some problem with my windows (.net) environment, I found these articles and forum posts about these dlls.

http://www.nirsoft.net/articles/windows_7_kernel_architecture_changes.html

http://social.msdn.microsoft.com/Forums/en-US/vsdebug/thread/9b8782c9-8fd4-484c-929f-9c8820765bc0/

(sadly I don't have CSLA installed)

**Comment by sebgod** [comment]
In fact the problem is that SWI Prolog does not use Visual Studio anymore to build SWI Prolog on Windows,
I think they use gcc for windows for that. So it's really hard to get it working correctly.
Actually I am already using a different approach, I'm running a HTTP Server in SWI Prolog and call that from node.js. It's just easier that way.

**Comment by bvarga** [comment]
Thanks for the hint, sounds s great workaround
